service: mcla-widget

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10

functions:
  widget:
    handler: handler.handler
    events:
      - http: any /
      - http: any /{proxy+}