service: mcla-widget

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10

functions:
  widget:
    handler: handler.handler
    events:
      - http: any /
      - http: any /{proxy+}
    environment:
      REST_URL:
        Fn::Join: ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.", { "Ref": "AWS::Region" }, ".amazonaws.com/${opt:stage}" ] ]